# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop
AllCops:
  TargetRubyVersion: 2.5.1

  Include:
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/environments/*'
    - 'config.ru'
Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
