default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: rails-graphql-experiment-dev

test:
  <<: *default
  database: rails-graphql-experiment-test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
